const ActionTypes = {
    LOGOUT: 'PLAYER/ LOGOUT',
    VALIDATE: 'PLAYER/ VALIDATE',
    AUTHORIZE: 'PLAYER/ AUTHORIZE',
    FETCH_DETAILS: 'PLAYER/ FETCH DETAILS',
    UPDATE_STATS: 'PLAYER/ UPDATE STATS'
};

export default ActionTypes;