const ActionTypes = {
    LOGOUT: 'PLAYER/ LOGOUT',
    VALIDATE: 'PLAYER/ VALIDATE',
    AUTHORIZE: 'PLAYER/ AUTHORIZE',
    FETCH_DETAILS: 'PLAYER/ FETCH DETAILS',
    UPDATE_STATS: 'PLAYER/ UPDATE STATS',
    UPDATE_SPEED_UPS: 'PLAYER/ UPDATE SPEED UPS',
    UPDATE_RESOURCES: 'PLAYER/ UPDATE RESOURCES'
};

export default ActionTypes;